"""Emit pyrightconfig.json so an editor's language server finds the venv.

`make lint` runs pyright through `uv run`, which puts the dev virtualenv on the
interpreter path first. An editor does not: nvim, VS Code and Zed launch pyright
directly, it looks for a `.venv` beside `pyproject.toml`, finds none -- decision
17 keeps the virtualenv outside the repository, because `omarchy plugin validate`
rejects symlinks inside a plugin folder -- and reports every third-party import
as unresolved. Eighty-four of them, none of which is a real problem.

`venvPath` fixes it, and cannot be committed: it is an absolute path containing
somebody's home directory, and pyright expands neither `~` nor an environment
variable. So it is generated, per machine, and git-ignored.

**The whole config is generated, not just the venv.** pyright does not merge the
two files -- a `pyrightconfig.json` next to a `pyproject.toml` replaces its
`[tool.pyright]` table entirely -- so a file carrying only the venv would
silently drop the strictness settings and the per-directory execution
environments, and the editor would disagree with CI about what an error is.
`pyproject.toml` stays the single source; this copies it and adds two keys.

Run `make lsp`. `make check` fails if the file exists and has gone stale.
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
import tomllib

HEADER = (
    "// Generated by `make lsp`. Do not edit by hand, and do not commit it:\n"
    "// the paths below are this machine's. Settings come from [tool.pyright] in\n"
    "// pyproject.toml; re-run `make lsp` after changing them.\n"
)


def main() -> int:
    """Write the config to stdout, or say why it cannot be built."""
    venv = os.environ.get("UV_PROJECT_ENVIRONMENT")
    if not venv:
        print(
            "UV_PROJECT_ENVIRONMENT is not set, so the virtualenv cannot be "
            "located. Run this through `make lsp` rather than directly.",
            file=sys.stderr,
        )
        return 1

    root = pathlib.Path(__file__).resolve().parents[1]
    with (root / "pyproject.toml").open("rb") as handle:
        config = tomllib.load(handle)["tool"]["pyright"]

    # ``venvPath`` is the directory *containing* the environment and ``venv`` its
    # name, which is why this is a split rather than one path.
    path = pathlib.Path(venv)
    config["venvPath"] = str(path.parent)
    config["venv"] = path.name

    # pyright reads JSON with comments, so the file can say what wrote it.
    print(HEADER + json.dumps(config, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
