"""Emit TOOLS.md from the server's own schemas.

Hand-written tool documentation drifts from the schemas within a release, and
the schemas are what a client actually sees. Run `make tools`.
"""

from __future__ import annotations

import asyncio
import json
import logging

from mcp.server.mcpserver import MCPServer

from omarchy_mcp import __version__
from omarchy_mcp.config import Config
from omarchy_mcp.policy import GUARDED_GROUPS, GUARDED_ROUTES
from omarchy_mcp.tools import generic

HEADER = f"""<!-- Generated by `make tools`. Do not edit by hand. -->

# Tools

The tool surface of the Omarchy MCP server, version {__version__}.

Omarchy ships hundreds of commands. Exposing one tool per command would put tens
of thousands of tokens of schema into a client's context before it did any work,
so discovery and dispatch are separate: **search** to find out what exists,
**run** to do it.

"""


def _annotation_words(annotations) -> str:
    if annotations is None:
        return "—"
    # 2.x exposes these snake_cased on the object and camelCased on the wire.
    flags = []
    if annotations.read_only_hint:
        flags.append("read-only")
    if annotations.destructive_hint:
        flags.append("destructive")
    if annotations.idempotent_hint:
        flags.append("idempotent")
    if annotations.open_world_hint:
        flags.append("open-world")
    return ", ".join(flags) or "—"


def _params(schema: dict) -> list[str]:
    required = set(schema.get("required") or ())
    lines = []
    for name, spec in (schema.get("properties") or {}).items():
        type_ = spec.get("type") or "any"
        if "anyOf" in spec:
            # Escaped: a bare pipe would end the table cell.
            type_ = r" \| ".join(o.get("type", "any") for o in spec["anyOf"])
        mark = "**required**" if name in required else "optional"
        default = spec.get("default")
        if default is None:
            suffix = ""
        else:
            # JSON spelling, since that is what a client will send.
            shown = json.dumps(default)
            suffix = f", default `{shown}`"
        lines.append(f"| `{name}` | `{type_}` | {mark}{suffix} |")
    return lines


async def render() -> str:
    mcp = MCPServer(name="omarchy", version=__version__)
    generic.register(mcp, Config(), logging.getLogger("doc"))
    tools = await mcp.list_tools()

    out = [HEADER, f"## The {len(tools)} tools\n"]
    out.append("| Tool | Behaviour |")
    out.append("|------|-----------|")
    for tool in sorted(tools, key=lambda t: t.name):
        out.append(f"| [`{tool.name}`](#{tool.name}) | {_annotation_words(tool.annotations)} |")
    out.append("")

    for tool in sorted(tools, key=lambda t: t.name):
        out.append(f"### `{tool.name}`\n")
        out.append(f"{tool.description}\n")
        rows = _params(tool.input_schema)
        if rows:
            out.append("| Parameter | Type | |")
            out.append("|-----------|------|--|")
            out.extend(rows)
            out.append("")

    out.append("## Policy\n")
    out.append(
        "Every command is classified from `omarchy commands --json`. "
        "`omarchy_search_commands` reports the tier of each result.\n"
    )
    out.append("| Tier | Rule | Behaviour |")
    out.append("|------|------|-----------|")
    out.append(
        "| `blocked` | needs sudo | Refused always. The server has no controlling "
        "terminal, so a password prompt could never be answered. Not overridable |"
    )
    out.append(
        "| `guarded` | destructive | Refused unless allowed in "
        "`~/.config/omarchy/mcp/config.toml` |"
    )
    out.append("| `safe` | everything else | Runs |")
    out.append("")
    out.append("Guarded groups: " + ", ".join(f"`{g}`" for g in sorted(GUARDED_GROUPS)) + ".\n")
    out.append(
        "Individually guarded routes: "
        + ", ".join(f"`{r}`" for r in sorted(GUARDED_ROUTES))
        + ".\n"
    )
    return "\n".join(out)


if __name__ == "__main__":
    print(asyncio.run(render()))
